INSERT INTO USER_PERMISSIONS (USER_ID,PERMISSIONGROUP_ID)
VALUES ((SELECT USER_ID FROM USERS WHERE USERS.USERNAME = ?),
(SELECT PERMISSIONGROUP_ID FROM PERMISSION_GROUPS WHERE PERMISSION_GROUPS.PERMISSION_NAME = ?));