SELECT DISTINCT  APPS.APP_NAME FROM APPS
LEFT JOIN PERMISSION_GROUPS ON APPS.ADMINPERMISSIONGROUP_ID = PERMISSION_GROUPS.PERMISSIONGROUP_ID
LEFT JOIN USER_PERMISSIONS ON USER_PERMISSIONS.PERMISSIONGROUP_ID = PERMISSION_GROUPS.PERMISSIONGROUP_ID
LEFT JOIN USERS ON USERS.USER_ID = USER_PERMISSIONS.USER_ID
WHERE USERS.USERNAME = ?