SELECT SUBSTRING(DYNAMIC_TABLES.TABLE_NAME, INSTR(DYNAMIC_TABLES.TABLE_NAME,'_')+1,LENGTH(DYNAMIC_TABLES.TABLE_NAME)) AS TABLENAME FROM DYNAMIC_TABLES
LEFT JOIN APPS ON APPS.APP_ID = DYNAMIC_TABLES.APP_ID
WHERE APPS.APP_NAME = ?