SELECT APP_PERMISSIONS.PERMISSION_TYPE FROM PERMISSION_GROUPS
LEFT JOIN APP_PERMISSIONS ON APP_PERMISSIONS.PERMISSIONGROUP_ID = PERMISSION_GROUPS.PERMISSIONGROUP_ID
WHERE PERMISSION_GROUPS.PERMISSION_NAME = ? AND 
APP_PERMISSIONS.TABLE_ID=(SELECT TABLE_ID FROM DYNAMIC_TABLES WHERE DYNAMIC_TABLES.TABLE_NAME = ?)