SELECT PERMISSION_GROUPS.PERMISSION_NAME,APP_PERMISSIONS.PERMISSION_TYPE FROM APP_PERMISSIONS
LEFT JOIN DYNAMIC_TABLES ON DYNAMIC_TABLES.TABLE_ID = APP_PERMISSIONS.TABLE_ID
LEFT JOIN PERMISSION_GROUPS ON PERMISSION_GROUPS.PERMISSIONGROUP_ID = APP_PERMISSIONS.PERMISSIONGROUP_ID
WHERE DYNAMIC_TABLES.TABLE_NAME = ?