SELECT USER_PERMISSIONS.* FROM USER_PERMISSIONS
LEFT JOIN USERS ON USERS.USER_ID = USER_PERMISSIONS.USER_ID
LEFT JOIN PERMISSION_GROUPS ON USER_PERMISSIONS.PERMISSIONGROUP_ID = PERMISSION_GROUPS.PERMISSIONGROUP_ID
WHERE USERS.USERNAME = ? AND PERMISSION_GROUPS.PERMISSION_NAME = ?