SELECT APP_PERMISSIONS.PERMISSION_TYPE FROM USERS
RIGHT JOIN USER_PERMISSIONS ON USERS.USER_ID = USER_PERMISSIONS.USER_ID
RIGHT JOIN PERMISSION_GROUPS ON USER_PERMISSIONS.PERMISSIONGROUP_ID = PERMISSION_GROUPS.PERMISSIONGROUP_ID
LEFT JOIN APP_PERMISSIONS ON APP_PERMISSIONS.PERMISSIONGROUP_ID = PERMISSION_GROUPS.PERMISSIONGROUP_ID
WHERE USERS.USERNAME = ? AND 
APP_PERMISSIONS.APP_ID=(SELECT APP_ID FROM APPS WHERE APPS.APP_NAME = ?) AND
APP_PERMISSIONS.TABLE_ID=(SELECT TABLE_ID FROM DYNAMIC_TABLES WHERE DYNAMIC_TABLES.TABLE_NAME = ?)