SELECT USERS.USER_ID, USERS.USERNAME, USERS.NAME, USERS.EMAIL, USERS.DATE_REGISTERED, USERS.YEAR, USERS.DISPLAY_NAME, USERS.ROOM_NUM, USERS.PHONE_PRE, USERS.PHONE_SUF,
TEMP_KEYS.KEY, USERS.EXPIRE_TS 
RIGHT JOIN TEMP_KEYS ON USERS.USER_ID = TEMP_KEYS.USER_ID
FROM USERS WHERE USERNAME = ? AND TEMP_KEYS.APP_ID = ?