SELECT DYNAMIC_TABLES.TABLE_NAME ,APP_PERMISSIONS.PERMISSION_TYPE FROM USERS
RIGHT JOIN USER_PERMISSIONS ON USERS.USER_ID = USER_PERMISSIONS.USER_ID
RIGHT JOIN PERMISSION_GROUPS ON USER_PERMISSIONS.PERMISSIONGROUP_ID = PERMISSION_GROUPS.PERMISSIONGROUP_ID
LEFT JOIN APP_PERMISSIONS ON APP_PERMISSIONS.PERMISSIONGROUP_ID = PERMISSION_GROUPS.PERMISSIONGROUP_ID
RIGHT JOIN DYNAMIC_TABLES ON APP_PERMISSIONS.APP_ID = DYNAMIC_TABLES.APP_ID
WHERE USERS.USERNAME = ? AND 
APP_PERMISSIONS.APP_ID=(SELECT APP_ID FROM APPS WHERE APPS.APP_NAME = ?) AND