SELECT USERS.USERNAME, APPS.APP_NAME TEMP_KEYS.EXPIRE_TS, UNIX_TIMESTAMP(NOW()) - UNIX_TIMESTAMP(TEMP_KEYS.EXPIRE_TS) as SEC_DIFF, TEMP_KEYS.KEY
FROM TEMP_KEYS
RIGHT JOIN USERS ON USERS.USER_ID = TEMP_KEYS.USER_ID
RIGHT JOIN APPS ON APPS.APP_ID = TEMP_KEYS.APP_ID
WHERE USERS.USERNAME = ? AND APPS.APP_NAME = ? HAVING SEC_DIFF > 0