SELECT USERS.USER_ID, USERS.USERNAME, TEMP_KEYS.CREATION_DATE, UNIX_TIMESTAMP(CURRENT_TIMESTAMP()) - UNIX_TIMESTAMP(TEMP_KEYS.CREATION_DATE) as SEC_DIFF, TEMP_KEYS.KEY
FROM TEMP_KEYS
RIGHT JOIN USERS ON USERS.USER_ID = TEMP_KEYS.USER_ID
WHERE USERS.USERNAME = ? HAVING SEC_DIFF <= ?